# defaults: &defaults
#   host: 127.0.0.1
#   port: 27017
#   options:
#     w: 1
#     pool_size: 1
#     slave_ok: false
#     ssl: false

development:
  # <<: *defaults
  database: kitkat_development

test:
  # <<: *defaults
  database: kitkat_test
  w: 0

# set these environment variables on your prod server
production:
  # <<: *defaults
   database: kitkat
   uri: "mongodb://heroku:a0254619049149873ad95bdffa97429a@troup.mongohq.com:10061/app22276860"
   
   #"<%= ENV['MONGOHQ_URL'] %>"